"""Create Tables

Revision ID: 301deaa7c087
Revises: bdbdab25949c
Create Date: 2024-11-23 00:22:58.270856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301deaa7c087'
down_revision = 'bdbdab25949c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mypage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('balance_sustain_time', sa.Float(), nullable=False),
    sa.Column('horizontal_balance_ratio', sa.Float(), nullable=False),
    sa.Column('unbalance_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cop_pattern',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('x_cop', sa.Float(), nullable=False),
    sa.Column('y_cop', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['train.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sustain_time',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('balance_sustain_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['train.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('total_unbalance_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('total_unbalance_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('sustain_time')
    op.drop_table('cop_pattern')
    op.drop_table('mypage')
    # ### end Alembic commands ###
