"""Change Train table

Revision ID: a467ec4ebb71
Revises: 1477788ac0ef
Create Date: 2024-11-26 11:47:18.448077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a467ec4ebb71'
down_revision = '1477788ac0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
