"""Train table test

Revision ID: bdbdab25949c
Revises: 
Create Date: 2024-11-22 16:17:11.360524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbdab25949c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_balance_sustain_time', sa.Float(), nullable=False),
    sa.Column('cop_pattern', sa.String(), nullable=True),
    sa.Column('total_unbalance_count', sa.Integer(), nullable=False),
    sa.Column('horizontal_balance_ratio', sa.String(), nullable=True),
    sa.Column('self_feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train')
    # ### end Alembic commands ###
