"""Change balance_time type Float -> Integer in Train Table

Revision ID: deb95d4224e9
Revises: 301deaa7c087
Create Date: 2024-11-23 17:45:16.231807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb95d4224e9'
down_revision = '301deaa7c087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('total_balance_sustain_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.alter_column('total_balance_sustain_time',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
